Repository javascript-tutorial/bn.javascript.info, pull requests merged in 2019-10, with the labels that each got.

#2 Manuals and specifications
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: needs +1

#6 Code structure
  1-js/02-first-steps/02-structure/article.md
Labels: needs +1, review needed

#4 An Introduction to JavaScript
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1

#7 Minor fix
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: needs +1

#8 Garbage collection
  1-js/04-object-basics/02-garbage-collection/article.md
Labels: needs +1

#10 Developer console
  1-js/01-getting-started/4-devtools/article.md
Labels: needs +1

#12 The modern mode, "use strict"
  1-js/02-first-steps/03-strict-mode/article.md
Labels: needs +1

#13 translate code-editors page
  1-js/01-getting-started/3-code-editors/article.md
Labels: changes requested

#14 Revert "translate code-editors page"
  1-js/01-getting-started/3-code-editors/article.md
Labels: review needed

#15 translate again code-editors page
  1-js/01-getting-started/3-code-editors/article.md
Labels: needs +1

#16 Revert "Code editors"
  1-js/01-getting-started/3-code-editors/article.md
Labels: review needed

#18 Code editors
  1-js/01-getting-started/3-code-editors/article.md
Labels: needs +1

#11 Hello, world!
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1

#9 Type Conversions
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/06-type-conversions/article.md
Labels: needs +1

#21 Interaction: alert, prompt, confirm
  1-js/02-first-steps/09-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/09-alert-prompt-confirm/article.md
Labels: needs +1

#22 Objects
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/_js.view/solution.js
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/_js.view/source.js
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/01-object/article.md
Labels: needs +1

#23 Polyfills
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1
